# Generated by Django 3.0.2 on 2020-01-26 10:46

from django.db import migrations

OBJECTS_TO_CREATE = 5


def generate_initial_data(apps, schema_editor):
    Person = apps.get_model('concierge', 'Person')
    Apartment = apps.get_model('concierge', 'Apartment')
    Key = apps.get_model('concierge', 'Key')
    for i in range(OBJECTS_TO_CREATE):
        apartment = Apartment(number=i)
        apartment.save()
        key = Key(apartment=apartment)
        key.save()
        person = Person(name=f'test_person_name_{i}')
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_data),
    ]
